# A deployment and clusterIP service for httpbin. So you can do some tests from within the cluster.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpbin
    tier: app
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      tier: app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpbin
        tier: app
    spec:
      containers:
        - image: kennethreitz/httpbin
          name: httpbin
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 1000m
              memory: 500Mi
          securityContext:
            # runAsUser: 999      # These settings cause the pod to fail in nonprod9 cluster.
            # runAsNonRoot: true
            # capabilities:
            #   drop:
            #     - "ALL"
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
---  
apiVersion: v1
kind: Service
metadata:
  name: httpbin-cip
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: httpbin
  type: ClusterIP
