apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu-helper
    tier: app
  name: ubuntu-helper
  annotations:
    about: "I am a helper pod for troubleshooting. Feel free to delete me if I have been here for a while."
spec:
  # ttlSecondsAfterFinished: 3  # Automatically delete the pod 1 hour after completion
  containers:
  - image: jrkessl/ubuntu:latest
    name: ubuntu-helper
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 250m
        memory: 200Mi
      requests:
        cpu: 250m
        memory: 200Mi
    command: ["/bin/sh", "-c", "sleep 28800"] # 28800 = 8 hours
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - "ALL"    
  terminationGracePeriodSeconds: 0
  dnsPolicy: ClusterFirst
  restartPolicy: Never
