apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-helper
  labels:
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
        app: ubuntu-helper
        tier: app
  template:
    metadata:
      labels:
        app: ubuntu-helper
        tier: app
    spec:
      containers:
      - name: ubuntu
        resources:
          limits:
            cpu: 250m
            memory: 200Mi
          requests:
            cpu: 250m
            memory: 200Mi
        imagePullPolicy: Always
        image: jrkessl/ubuntu
        command: ["/bin/sh", "-c", "sleep infinity"]
        securityContext:
          runAsUser: 999
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - "ALL"