apiVersion: v1
kind: Service
metadata:
  name: meunginx
spec:
  type: LoadBalancer    
  # loadBalancerSourceRanges: # Optional: this adds rules in the security group of the AWS load balancer.
  #   - 189.18.90.14/32
  ports: 
    - port: 80
  selector: 
    app: meunginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meunginx
spec:
  selector:
    matchLabels:
      app: meunginx
  replicas: 1
  template:
    metadata:
      labels:
        app: meunginx
    spec:
      containers:
        - image: nginx:latest
          name: meunginx
          # ports:
          #   - containerPort: 80